name: kt-lms-dev


services:
  moodle:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./moodle:/var/www/html
      - ./moodle-data:/var/www/moodledata
    environment:
      PHP_EXTENSION_xdebug: 1
    ports:
      - "8080:80"
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodlepass
      POSTGRES_DB: moodle
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "35432:5432"


volumes:
  pg_data:
